version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: clicks-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
            - redis
            - clickhouse
        networks:
            - clicks

    nginx:
        image: nginx:stable-alpine
        container_name: clicks-nginx
        restart: unless-stopped
        ports:
            - "8081:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        depends_on:
            - app
        networks:
            - clicks

    mysql:
        image: mysql:8.0
        container_name: clicks-mysql
        restart: unless-stopped
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - clicks

    redis:
        image: redis:alpine
        container_name: clicks-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - clicks

    clickhouse:
        image: clickhouse/clickhouse-server:latest
        container_name: clicks-clickhouse
        restart: unless-stopped
        ports:
            - "${DB_PORT_CLICKHOUSE:-8123}:8123"
        environment:
            CLICKHOUSE_DB: ${DB_DATABASE_CLICKHOUSE}
            CLICKHOUSE_USER: ${DB_USERNAME_CLICKHOUSE}
            CLICKHOUSE_PASSWORD: ${DB_PASSWORD_CLICKHOUSE}
            CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
        volumes:
            - clickhouse-data:/var/lib/clickhouse
        networks:
            - clicks

networks:
    clicks:

volumes:
    mysql-data:
    clickhouse-data:
